CREATE TABLE pesanan
(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_user INT NOT NULL,
    id_rekap INT DEFAULT NULL,
    tanggal DATE NOT NULL DEFAULT GETDATE(),
    pembayaran BOOL NOT NULL DEFAULT(FALSE),
    CONSTRAINT FK_UserPesanan FOREIGN KEY (id_user) REFERENCES users(id),
    CONSTRAINT FK_RekapPesanan FOREIGN KEY (id_rekap) REFERENCES rekap(id)
) ENGINE = InnoDB;